DISKSTATION_ADMIN=""
DISKSTATION_HOST = ''
DISKSTATION_PORT = 22
DISKSTATION_USERS = ()
DISKSTATION_WEBMASTER = ""
DISKSTATION_WORDPRESS_BACKUP = ""
DISKSTATION_WORDPRESS_BACKUP_DIRECTORY = ""
DISKSTATION_WEB_DIRECTORY = ""

SANDBOX_HOST = ""
SANDBOX_USERS = ()
SANDBOX_PORT = 22

BACKUPS_DIRECTORY = ""
DROPBOX_BACKUPS_DIRECTORY = ""
SSH_KEY = ""

# codespaces
CODESPACE_COPTHIS = {
    "NAME": "",
    "PATH": "",
    "FILENAMES": (),
}
CODESPACE_COPTHIS_WEBSITE = {
    "NAME": "",
    "PATH": "",
    "FILENAMES": (),
}
CODESPACE_MERCHBAR_WEB = {
    "NAME": "",
    "PATH": "",
    "FILENAMES": (),
}

LOCAL_USER=''
LOCAL_COPTHIS_CONFIG=''
LOCAL_SHARETRIBE_CONFIG=''
LOCAL_MERCHBAR_WEB_CONFIG=''
